const fs = require("fs");
const path = require("path");
const { parseArgs } = require("util");

// -------------------------------
// CONSTANTS
// -------------------------------

/**
 * If you need to customize the Rojo tree, output directories, or package paths, do not edit this file.
 * Instead, create a '.rogen.json` in the root of your project.
 */
const FALLBACK_CONFIG = `{
	"sourceDir": "src",
	"luau": { 
		"outFile": "default.project.json", 
		"outDir": "src", 
		"wrapper": false 
	},
	"ts": { 
		"outFile": "default.project.json", 
		"outDir": "out", 
		"wrapper": "TS" 
	},
	"darklua": { 
		"outFile": "build.project.json", 
		"outDir": "dist" 
	},
	"project": {
		"name": "roblox-project",
		"globIgnorePaths": [
			"**/package.json",
			"**/tsconfig.json"
		],
		"tree": {
			"$className": "DataModel",
			"ServerScriptService": {
				"ServerPackages": {
					"$path": "ServerPackages"
				}
			},
			"ReplicatedStorage": {
				"rbxts_include": {
					"$path": "include",
					"node_modules": { 
						"$className": "Folder", 
						"@rbxts": { 
							"$path": "node_modules/@rbxts" 
						}
					}
				},
				"Packages": {
					"$path": "Packages"
				}
			}
		}
	}
}`;

const services = {
	Server: "ServerScriptService",
	Client: "StarterPlayerScripts",
	Shared: "ReplicatedStorage",
	ServerScriptService: "ServerScriptService",
	ReplicatedStorage: "ReplicatedStorage",
	ReplicatedFirst: "ReplicatedFirst",
	ServerStorage: "ServerStorage",
	StarterGui: "StarterGui",
	StarterPack: "StarterPack",
	StarterPlayerScripts: "StarterPlayerScripts",
	StarterCharacterScripts: "StarterCharacterScripts",
};

const serviceParents = {
	StarterPlayerScripts: "StarterPlayer",
	StarterCharacterScripts: "StarterPlayer",
};

const lowerServiceMap = Object.fromEntries(Object.entries(services).map(([k, v]) => [k.toLowerCase(), v]));
const separatorRegex = new RegExp(`[\\.\\-_](${Object.keys(lowerServiceMap).join("|")})$`, "i");
const pascalCaseRegex = new RegExp(`(${Object.keys(services).join("|")})$`);

// -------------------------------
// CLI
// -------------------------------

const options = {
	config: { type: "string", short: "c" },
	mode: { type: "string", short: "m" },
	project: { type: "string", short: "p" }
};

const { values: cliArgs } = parseArgs({ options, strict: false });

// -------------------------------
// CONFIG HANDLING
// -------------------------------

function resolveConfigPath(customPathArg) {
	if (customPathArg) {
		const resolvedPath = path.resolve(process.cwd(), customPathArg);
		if (!fs.existsSync(resolvedPath)) {
			throw new Error(`Specified config file not found: ${customPathArg}`);
		}
		return resolvedPath;
	}

	const explicitDefaultPath = path.resolve(process.cwd(), "default.rogen.json");
	if (fs.existsSync(explicitDefaultPath)) return explicitDefaultPath;

	const alternateDefaultPath = path.resolve(process.cwd(), ".rogen.json");
	if (fs.existsSync(alternateDefaultPath)) return alternateDefaultPath;

	return null;
}

function loadAndValidateConfig(configPath) {
	if (!configPath) {
		return { 
			config: JSON.parse(JSON.stringify(FALLBACK_CONFIG)), 
			hasConfig: false 
		};
	}

	const config = JSON.parse(fs.readFileSync(configPath, "utf-8"));
	const standardKeys = ["sourceDir", "project", "luau", "ts", "darklua"];

	for (const key in config) {
		if (!standardKeys.includes(key)) {
			const customMode = config[key];
			if (typeof customMode !== "object" || customMode === null || Array.isArray(customMode)) {
				throw new Error(`\nConfiguration Error: Root key "${key}" must be a valid object defining a build mode.\n`);
			}
		} else if (key === "project" && typeof config[key] !== "object" && typeof config[key] !== "string") {
			throw new Error(`\nConfiguration Error: 'project' must be an inline object or a string path to a JSON file.\n`);
		}
	}

	return { config, hasConfig: true };
}

function loadProjectTree(cliProjectArg, configProjectField) {
	let targetPath = null;
	
	if (cliProjectArg) {
		targetPath = path.resolve(process.cwd(), cliProjectArg);
	}
	else if (typeof configProjectField === "string") {
		targetPath = path.resolve(process.cwd(), configProjectField);
	}

	if (targetPath) {
		if (!fs.existsSync(targetPath)) {
			throw new Error(`Specified project file not found: ${targetPath}`);
		}
		return JSON.parse(fs.readFileSync(targetPath, "utf-8"));
	}

	if (typeof configProjectField === "object" && configProjectField !== null) {
		return configProjectField;
	}
	return JSON.parse(JSON.stringify(FALLBACK_CONFIG.project));
}

function getEnvironment() {
	const isTsProject = fs.existsSync(path.join(process.cwd(), "tsconfig.json"));
	const isDarkluaProject = fs.existsSync(path.join(process.cwd(), ".darklua.json")) 
		|| fs.existsSync(path.join(process.cwd(), ".darklua.json5"));
	
	return { isTsProject, isDarkluaProject };
}

function resolveActiveModes(config, hasConfig, cliMode, env) {
	const baseLanguage = env.isTsProject 
		? (config.ts || FALLBACK_CONFIG.ts) 
		: (config.luau || FALLBACK_CONFIG.luau);
	
	const activeModes = [];

	if (hasConfig) {
		if (cliMode) {
			if (!config[cliMode]) {
				throw new Error(`Mode "${cliMode}" is not defined in your config file.`);
			}
			const selectedMode = config[cliMode];
			if (selectedMode.wrapper === undefined) selectedMode.wrapper = baseLanguage.wrapper;
			activeModes.push(selectedMode);
		} else {
			for (const key in config) {
				if (key !== "sourceDir" && key !== "project" && typeof config[key] === "object" && !Array.isArray(config[key])) {
					if (key === "luau" && env.isTsProject) continue;
					if (key === "ts" && !env.isTsProject) continue;
					if (key === "darklua" && !env.isDarkluaProject) continue;

					const selectedMode = config[key];
					if (selectedMode.wrapper === undefined) selectedMode.wrapper = baseLanguage.wrapper;
					activeModes.push(selectedMode);
				}
			}
			if (activeModes.length === 0) {
				throw new Error("No output modes defined in configuration file. Add 'luau', 'ts', or custom modes.");
			}
		}
	} else {
		if (cliMode) {
			if (!config[cliMode]) {
				throw new Error(`Mode "${cliMode}" is not defined in the fallback config.`);
			}
			activeModes.push({ ...baseLanguage, ...config[cliMode] });
		} else {
			activeModes.push(baseLanguage);
			if (env.isDarkluaProject) {
				activeModes.push({ ...baseLanguage, ...config.darklua });
			}
		}
	}

	return activeModes;
}

// -------------------------------
// PATH & TREE UTILS
// -------------------------------

const toPosix = (p) => p.split(path.sep).join("/");
const isScript = (filename) => /\.(tsx?|luau|lua)$/i.test(filename) && !filename.toLowerCase().endsWith(".d.ts");
const isModel = (filename) => /\.(rbxm|rbxmx)$/i.test(filename);
const isValidSource = (filename) => isScript(filename) || isModel(filename);
const isInitFile = (filename) => isScript(filename) && /^(index|init)([\.-][a-z0-9_]+)?\./i.test(filename);

function getOrCreateNode(parent, key, className) {
	if (!parent[key]) {
		parent[key] = className == null ? {} : { "$className": className };
	}
	return parent[key];
}

function resolveRoute(relativePath, isInit, { emitLegacyScripts, isTsProject, outDir }) {
	const parts = relativePath.split(path.sep);
	const filename = parts.pop();
	const basename = path.basename(filename, path.extname(filename));

	let targetService = "ReplicatedStorage";
	const virtualParts = [];
	let lastRouteKeyword = null;

	// Folder routing
	for (const part of parts) {
		const lowerPart = part.toLowerCase();
		
		if (lowerServiceMap[lowerPart]) {
			targetService = lowerServiceMap[lowerPart];
			lastRouteKeyword = lowerPart;
		}

		virtualParts.push(part);
	}

	let matchedSuffixLength = 0;
	let mappedService = null;

	const sepMatch = basename.match(separatorRegex);
	const pascalMatch = basename.match(pascalCaseRegex);

	// Suffix routing
	if (sepMatch) {
		mappedService = lowerCaseServiceMap[sepMatch[1].toLowerCase()];
		matchedSuffixLength = sepMatch[0].length;
		if (!isInit) {
			virtualParts.push(sepMatch[1]);
		}
	} else if (pascalMatch) {
		mappedService = services[pascalMatch[1]];
		matchedSuffixLength = pascalMatch[0].length;
		if (!isInit) {
			virtualParts.push(pascalMatch[1]);
		}
	}

	// Scripts with non-legacy RunContext run incorrectly in StarterPlayer container.
	// Instead, always put them in ReplicatedStorage
	const isStarterPlayerContainer = targetService === "StarterPlayerScripts" || targetService === "StarterCharacterScripts";
	if (emitLegacyScripts === false && isStarterPlayerContainer) {
		targetService = "ReplicatedStorage";
	}

	let nodeName = basename;
	let projectPath = "";

	if (isInit) {
		const folderRelativePath = path.dirname(relativePath);
		projectPath = toPosix(path.join(outDir, folderRelativePath));
		if (virtualParts.length > 0) {
			nodeName = virtualParts.pop();
		} else {
			nodeName = lastRouteKeyword ? lastRouteKeyword : "source";
		}
	} else {
		let compiledRelativePath = relativePath;
		
		// Roblox-ts projects need to swap .ts/.tsx extensions to .luau
		if (isTsProject) {
			const compiledFilename = filename.replace(/\.tsx?$/i, ".luau");
			compiledRelativePath = path.join(path.dirname(relativePath), compiledFilename);
		}
		
		projectPath = toPosix(path.join(outDir, compiledRelativePath));
		
		if (mappedService) {
			nodeName = basename.slice(0, -matchedSuffixLength);
		}
	}

	return { targetService, virtualParts, nodeName, projectPath };
}

function walk(dir, callback) {
	if (!fs.existsSync(dir)) return;
	
	const entries = fs.readdirSync(dir, { withFileTypes: true });
	const initFile = entries.find((e) => e.isFile() && isInitFile(e.name));

	if (initFile) {
		callback(path.join(dir, initFile.name), true);
		// Rojo automatically syncs the entire directory when mapped to an init file.
		// Return early so we don't create duplicate explicit entries for children.
		return;
	}

	for (const entry of entries) {
		const fullPath = path.join(dir, entry.name);
		if (entry.isDirectory()) {
			walk(fullPath, callback);
		} else if (isValidSource(entry.name)) {
			callback(fullPath, false);
		}
	}
}

function pruneObject(node, outDir) {
	for (const key in node) {
		const val = node[key];
		if (typeof val !== "object" || val === null) continue;

		if (val.$path) {
			if (val.$path.startsWith(outDir)) {
				continue; 
			}
			
			if (!fs.existsSync(path.resolve(process.cwd(), val.$path))) {
				delete node[key];
				continue;
			}
		}
		pruneObject(val, outDir);
	}
	return node;
}

function sortObject(obj) {
	if (obj === null || typeof obj !== "object" || Array.isArray(obj)) return obj;
	return Object.keys(obj)
		.sort()
		.reduce((acc, key) => {
			acc[key] = sortObject(obj[key]);
			return acc;
		}, {});
}

// -------------------------------
// EXECUTION
// -------------------------------

function build(targetConfig, config, sourcePath, env, baseProjectTree) {
	const rojoTree = JSON.parse(JSON.stringify(baseProjectTree));
	rojoTree.tree = rojoTree.tree || { $className: "DataModel" };

	const context = {
		sourceDir: config.sourceDir || "src",
		...targetConfig,
		isTsProject: env.isTsProject,
		emitLegacyScripts: rojoTree.emitLegacyScripts ?? true,
		name: rojoTree.name ?? "unknown",
	};

	if (!context.outDir || !context.outFile) {
		throw new Error(`Invalid configuration: Target mode must specify 'outDir' and 'outFile'.\nReceived: ${JSON.stringify(targetConfig)}`);
	}

	let fileCount = 0;
	walk(sourcePath, (filepath, isInit) => {
		fileCount++;

		const relativePath = path.relative(sourcePath, filepath);
		const { targetService, virtualParts, nodeName, projectPath } = resolveRoute(relativePath, isInit, context);
		
		let current = rojoTree.tree;

		if (serviceParents[targetService]) {
			current = getOrCreateNode(current, serviceParents[targetService]);
		}
		current = getOrCreateNode(current, targetService);

		if (context.wrapper) {
			current = getOrCreateNode(current, context.wrapper, "Folder");
		}

		for (const part of virtualParts) {
			current = getOrCreateNode(current, part, "Folder");
		}

		current[nodeName] = { ...current[nodeName], $path: projectPath };
		if (current[nodeName]["$className"] === "Folder") {
			delete current[nodeName]["$className"];
		}
	});

	const prunedTree = pruneObject(rojoTree, context.outDir);
	const sortedTree = sortObject(prunedTree);
	const newContent = JSON.stringify(sortedTree, null, 2);

	let shouldWrite = true;
	if (fs.existsSync(context.outFile)) {
		const existingContent = fs.readFileSync(context.outFile, "utf-8");
		if (existingContent === newContent) {
			shouldWrite = false;
		}
	}

	if (shouldWrite) {
		fs.writeFileSync(context.outFile, newContent);
		console.log(`\nSuccess! Generated Rojo tree for "${context.name}"`);
		console.log(`   OutDir:    ${context.outDir}`);
		console.log(`   Processed: ${fileCount} source files`);
		console.log(`   OutFile:   ${context.outFile}\n`);
	}
}

async function main() {
	const configPath = resolveConfigPath(cliArgs.config);
	const { config, hasConfig } = loadAndValidateConfig(configPath);
	
	const sourceDir = config.sourceDir || "src";
	const sourcePath = path.resolve(process.cwd(), sourceDir);
	
	if (!fs.existsSync(sourcePath)) {
		throw new Error(`Source directory not found: ${sourcePath}`);
	}

	const env = getEnvironment();
	const activeModes = resolveActiveModes(config, hasConfig, cliArgs.mode, env);
	const baseProjectTree = loadProjectTree(cliArgs.project, config.project);

	for (const targetConfig of activeModes) {
		build(targetConfig, config, sourcePath, env, baseProjectTree);
	}
}

main().catch((error) => {
	console.error(`\nBuild Failed: ${error.message}\n`);
	process.exit(1);
});
